[package]
name = "pitpls-app"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pitpls-core.workspace = true
pitpls-db.workspace = true
pitpls-importers.workspace = true
pitpls-nbr.workspace = true

chrono.workspace = true
reqwest.workspace = true
rust_decimal.workspace = true
serde = { version = "1", features = ["derive"] }
specta = { version = "=2.0.0-rc.22", features = ["derive"] }
uuid.workspace = true
