[package]
name = "pitpls-db"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pitpls-core.workspace = true

chrono.workspace = true
rust_decimal.workspace = true
serde_plain = "1"
sqlx = { version = "0.8.6", features = ["chrono", "migrate", "runtime-tokio", "sqlite"] }
thiserror.workspace = true
