// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async importCsv(file: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv", { file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importApi(year: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_api", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetRates() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_rates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRates() : Promise<Result<RatesViewModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_rates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadCryptos(year: number | null) : Promise<Result<CryptoTaxData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_cryptos", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCryptos(ids: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cryptos", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCrypto(input: CreateCryptoInput) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_crypto", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCrypto(input: UpdateCryptoInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_crypto", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadDividends(year: number | null) : Promise<Result<DividendTaxData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_dividends", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDividends(ids: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dividends", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDividend(input: CreateDividendInput) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_dividend", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDividend(input: UpdateDividendInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dividend", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadInterests(year: number | null) : Promise<Result<InterestTaxData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_interests", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteInterests(ids: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_interests", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createInterest(input: CreateInterestInput) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_interest", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateInterest(input: UpdateInterestInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_interest", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runImport(kind: ImporterKind, file: string) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_import", { kind, file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWarnings(year: number | null) : Promise<Result<Warnings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_warnings", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadTaxSummary(year: number | null) : Promise<Result<TaxSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_tax_summary", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listYears() : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_years") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addYear(year: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_year", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteYear(year: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_year", { year }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSettings(settings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/

export const IMPORTERS = [{"input":["Csv"],"kind":"T212","name":"Trading 212","output":["Dividend","Interest"]},{"input":["Pdf"],"kind":"Revolut","name":"Revolut","output":["Dividend"]},{"input":["Csv"],"kind":"Coinbase","name":"Coinbase","output":["Crypto"]}] as const;

/** user-defined types **/

export type Action = "FiatBuy" | "FiatSell"
export type Amount = { value: string; currency: Currency }
export type CalculatedCrypto = { id: string; value: Amount; calculated_value: string; fee: Amount; calculated_fee: string; action: Action; date: string; nbp_date: string; provider: string }
export type CalculatedDividend = { id: string; date: string; nbp_date: string; ticker: string; value: Amount; calculated_value: string; calculated_to_pay: string; tax_paid: Amount; calculated_tax_paid: string; max_tax_paid: string; used_tax_paid: string; country: string; provider: string }
export type CalculatedInterest = { id: string; date: string; nbp_date: string; value: Amount; calculated_value: string; to_pay: string; provider: string }
export type CreateCryptoInput = { id: string | null; date: string; action: Action; value: string; value_currency: Currency; fee: string; fee_currency: Currency; provider: string }
export type CreateDividendInput = { id: string | null; date: string; ticker: string; value: string; value_currency: Currency; tax_paid: string; tax_paid_currency: Currency; country: string; provider: string }
export type CreateInterestInput = { id: string | null; date: string; value: string; value_currency: Currency; provider: string }
export type CryptoTaxData = { income: string; costs: string; calculated: CalculatedCrypto[] }
export type CryptoTaxSummary = { income: string; costs: string }
export type Currency = "EUR" | "USD" | "PLN"
export type DividendRounding = "SumToGroszy" | "SumToPayToZlote" | "SumBothToZlote" | "AllToZlote"
export type DividendTaxData = { to_pay: string; paid: string; income: string; calculated: CalculatedDividend[] }
export type ForeignTaxSummary = { income: string; tax_to_pay: string; tax_paid: string }
export type ImportResult = { dividends: number; cryptos: number; interests: number }
export type Importer = { kind: ImporterKind; name: string; input: InputType[]; output: OutputType[] }
export type ImporterKind = "T212" | "Revolut" | "Coinbase"
export type InputType = "Csv" | "Pdf"
export type InterestTaxData = { to_pay: string; income: string; calculated: CalculatedInterest[] }
export type OutputType = "Dividend" | "Crypto" | "Interest"
export type RateDay = { date: string; usd: string | null; eur: string | null }
export type RatesViewModel = { rows: RateDay[] }
export type Settings = { dividend_rounding: DividendRounding }
export type TaxSummary = { crypto: CryptoTaxSummary; foreign: ForeignTaxSummary }
export type UpdateCryptoInput = { id: string; date: string; action: Action; value: string; value_currency: Currency; fee: string; fee_currency: Currency; provider: string }
export type UpdateDividendInput = { id: string; date: string; ticker: string; value: string; value_currency: Currency; tax_paid: string; tax_paid_currency: Currency; country: string; provider: string }
export type UpdateInterestInput = { id: string; date: string; value: string; value_currency: Currency; provider: string }
export type Warnings = { rates_empty: boolean; has_records_in_year: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
